package com.example.sosjibon.ai

import android.content.Context
import org.json.JSONArray
import java.util.Locale

/**
 * Converts normal user text into the exact integer token format
 * expected by the SOS Jibon LiteRT intent classifier.
 *
 * Training configuration:
 * - Vocabulary size: 2000
 * - Actual exported vocabulary: 121
 * - Sequence length: 25
 * - Padding/truncation: 25 tokens
 * - Token 0: padding
 * - Token 1: unknown [UNK]
 */
class LocalTokenizer(
    context: Context
) {

    companion object {
        private const val VOCAB_FILE = "vocab.json"

        // Must exactly match the model's training sequence length.
        const val SEQUENCE_LENGTH = 25

        // TextVectorization vocabulary:
        // index 0 = ""
        // index 1 = "[UNK]"
        private const val UNKNOWN_INDEX = 1
    }

    private val vocabulary: Map<String, Int>

    init {
        vocabulary = loadVocabulary(context)
    }

    /**
     * Loads vocab.json from:
     *
     * app/src/main/assets/vocab.json
     */
    private fun loadVocabulary(context: Context): Map<String, Int> {

        val jsonText = context.assets
            .open(VOCAB_FILE)
            .bufferedReader()
            .use { it.readText() }

        val jsonArray = JSONArray(jsonText)

        val vocab = HashMap<String, Int>()

        for (index in 0 until jsonArray.length()) {
            val token = jsonArray.getString(index)

            // Keep the exact index generated by Keras.
            vocab[token] = index
        }

        return vocab
    }

    /**
     * Converts user text into a fixed-length IntArray.
     *
     * Example:
     *
     * "open my medical vault"
     *
     * becomes something like:
     *
     * [23, 14, 8, 31, 0, 0, 0, ...]
     *
     * The actual numbers come from vocab.json.
     */
    fun tokenize(text: String): IntArray {

        val normalizedText = normalizeText(text)

        if (normalizedText.isBlank()) {
            return IntArray(SEQUENCE_LENGTH)
        }

        val words = normalizedText
            .trim()
            .split(Regex("\\s+"))
            .filter { it.isNotBlank() }

        val result = IntArray(SEQUENCE_LENGTH)

        val tokenCount = minOf(
            words.size,
            SEQUENCE_LENGTH
        )

        for (i in 0 until tokenCount) {

            val word = words[i]

            result[i] = vocabulary[word]
                ?: UNKNOWN_INDEX
        }

        return result
    }

    /**
     * Reproduces the important behavior of Keras
     * TextVectorization standardization:
     *
     * lower-case
     * +
     * remove ASCII punctuation
     */
    private fun normalizeText(text: String): String {

        val lowercase = text.lowercase(Locale.ROOT)

        // Python string.punctuation used by Keras:
        //
        // !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
        //
        // We remove these characters instead of replacing them,
        // matching Keras lower_and_strip_punctuation behavior.
        val punctuationRegex =
            Regex("""[!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~]""")

        return lowercase.replace(
            punctuationRegex,
            ""
        )
    }

    /**
     * Useful for testing/debugging.
     *
     * Example:
     *
     * tokenizer.getTokenIds("open medical vault")
     */
    fun getTokenIds(text: String): List<Int> {
        return tokenize(text).toList()
    }

    /**
     * Returns the vocabulary size loaded from vocab.json.
     */
    fun vocabularySize(): Int {
        return vocabulary.size
    }
}